name: Boilerplate_NextJS
on:  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Deploy Boilerplate

  deploy-dev:
    runs-on: ubuntu-latest
    environment: 
      name: develop
      url: 'sysfactoring.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy develop
        
  deploy-hmg:
    runs-on: ubuntu-latest
    environment: 
      name: hmg
      url: 'sysfactoring.com'
    needs: deploy-dev
    steps:
      - name: Run a one-line script
        run: echo Deploy hmg
  
  deploy-prod:
    runs-on: ubuntu-latest
    environment: 
      name: hmg
      url: 'sysfactoring.com'
    needs: deploy-hmg
    steps:
      - name: Run a one-line script
        run: echo Deploy prod
